name: Hugo Build

on:
  push:
    branches:
      - main # Set a branch that will trigger a deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Deploy with rsync
        run: rsync -avz ./public/ ${{ secrets.SSH_USER }}@iamjannik.me:/var/www/blog.iamjannik.me

      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  if: github.ref == 'refs/heads/main'
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./public
